modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="lughna"
version="${0.0.1}"
displayName="Lughna"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/lughna"
displayURL="https://sites.google.com/view/mishais-hub"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to hypherionsa and nekosune, for all the help they gave me that made this mod possible."
authors="Love, Cheese, Eggs, and Mishainah."
description='''A Magic Mod made by Mishainah that's based on the theory of ley lines.'''
[[dependencies.lughna]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"
[[dependencies.lughna]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4,1.17)"
ordering="NONE"
side="BOTH"
